In [ ]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [ ]:
iris_X, iris_y = datasets.load_iris(as_frame=True, return_X_y=True)
iris_y.unique()

array([0, 1, 2])

In [ ]:
iris_X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
iris_y.unique()

array([0, 1, 2])

In [ ]:
iris_X.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [ ]:
iris_X['sepal length (cm)'] += 1
iris_X.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [ ]:
copy_iris = iris_X.copy()
copy_iris.columns = ['Sepal_length', 'Sepal_width', 'Petal_Length', 'Petal_width']
copy_iris.head()

Sepal_length  Sepal_width  Petal_Length  Petal_width
0           6.1          3.5           1.4          0.2
1           5.9          3.0           1.4          0.2
2           5.7          3.2           1.3          0.2
3           5.6          3.1           1.5          0.2
4           6.0          3.6           1.4          0.2

In [ ]:
iris_y.dtype

dtype('int64')

In [ ]:
iris_y.astype('int8')

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int8

In [ ]:
data = copy_iris.drop(['Sepal_length'], axis=1)
data.dropna()

Sepal_width  Petal_Length  Petal_width
0            3.5           1.4          0.2
1            3.0           1.4          0.2
2            3.2           1.3          0.2
3            3.1           1.5          0.2
4            3.6           1.4          0.2
..           ...           ...          ...
145          3.0           5.2          2.3
146          2.5           5.0          1.9
147          3.0           5.2          2.0
148          3.4           5.4          2.3
149          3.0           5.1          1.8

[150 rows x 3 columns]

In [ ]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b = np.random.rand(20,20)
b

array([[4.85368636e-01, 3.84965249e-01, 9.20876278e-01, 6.27489591e-01,
        6.62633646e-01, 2.38770227e-01, 6.93280989e-02, 9.49849662e-01,
        9.98927206e-01, 6.79523225e-01, 3.36808139e-01, 3.90517103e-01,
        9.41175112e-01, 7.79938804e-01, 1.85377914e-01, 7.03769469e-01,
        2.06794948e-01, 7.77108658e-01, 9.80223116e-01, 6.62524437e-01],
       [4.94002827e-01, 9.98257996e-01, 5.68943290e-02, 8.05515096e-01,
        8.55372662e-01, 1.49876610e-01, 3.08514571e-01, 6.94220455e-01,
        8.96614019e-01, 9.13808269e-01, 6.18683505e-01, 5.28858971e-01,
        6.22211162e-01, 8.59471467e-01, 8.64827245e-01, 4.93510355e-01,
        9.44657971e-01, 8.96079032e-01, 9.58523289e-01, 9.51030080e-02],
       [5.99782175e-02, 3.00740505e-01, 6.76055259e-01, 5.88928257e-01,
        2.29654855e-01, 1.45136448e-01, 2.61898297e-01, 2.22143543e-01,
        5.57854453e-01, 2.91065625e-01, 5.79303183e-01, 2.30060836e-02,
        5.41738980e-01, 7.92635368e-02, 2.85479993e-01, 1.0774

In [ ]:
a.shape

(20,)

In [ ]:
b.shape

(20, 20)

In [ ]:
c = np.random.randn(2, 15)
c.shape

(2, 15)

In [ ]:
c.transpose().shape

(15, 2)

In [ ]:
np.matmul(a, b).shape

(20,)

In [ ]:
(a @ b).shape

(20,)